---
layout: cv
title: Ketsiammen Peter's CV
---
# Ketsiammen Peter
aspiring Data Scientist

<a href="www.linkedin.com/in/ketsiammen-monthe-yann-peter-b690ab263">My linkedin page</a>
</div>


## Profile summary

Passionate data science and tech enthusiast eager to apply my academic knowledge and hands-on skills in a dynamic setting. Detail-oriented and dedicated individual with a strong foundation in Microsoft Office Suite, specializing in Word, PowerPoint, and Excel for document creation, presentations, and data entry. Proficient in leveraging Python for efficient problem-solving and scripting, with a focus on clean code practices. Experienced in MySQL for database management, showcasing abilities in data retrieval, manipulation, and basic optimization. Excited about expanding expertise in advanced database design and query optimization. Recognized for adaptability, quick learning, and a commitment to using technology for effective problem resolution. Seeking opportunities to contribute and grow in a challenging environment.



## Language
french(native), english(advanced)


## Education

`2022-now`
__Brigham Young University, Idaho.__

studying Data Science



## Experience

`March 2023`
Allen Design Company

Collaborated with Allen Designs, a small business in Las Vegas, Nevada, specializing in crafting functional and aesthetically pleasing interior spaces to address the needs in managing finances and executing effective digital marketing strategies.

improved company website by proposing various website template, Logos ,slogans and names.

Advised various marketing plans to help company reach more customers.


## skils

### computer skills

Microsoft Office Suite: Competent in utilizing essential functions of Word for document creation, PowerPoint for basic presentations, and Excel for fundamental data entry and spreadsheet tasks. 

Programming Languages and Database Management:  Python: Proficient in writing and debugging Python code, with a focus on problem-solving and scripting tasks.
 MySQL: Competent in database management using MySQL, including data retrieval, manipulation, and basic optimization. Eager to expand skills in database design and advanced query optimization.



<!-- ### Footer

Last updated: May 2013 -->